### ISSUE TITLE
Dataset names: semantics

### ISSUE THREAD

**Issue by tresoldi** [lexibank/lexibank#1]
Well, `asjp` is an exception as it would be an hypothetical `wiktionary` -- it is neither restricted to a family and it is already a data aggregation. I wouldn't matter closing an eye in this case, but it is important to refer to authors already in the dataset name, so that they know we are actually collaborating and not appropriating (pretty much what @LinguList said on a previous email).

**Comment by xrotwang** [comment]
While I agree that highlighting contributions is important, I don't necessarily think this has to be done in the dataset name. ASJP is a good example - I'd say the acronym ASJP alone probably evokes "Holman and Wichmann" more, than when only one of the two is appended to it.

**Comment by SimonGreenhill** [comment]
I think it makes sense that databases should get their database names .  It's the published ones that are problematic (e.g. why 'chapacuran' and not 'birchalletal2016' or why 'huber**and**reed' but 'tryonhackman').

I think there's also an issue with namespace clashes on PyPI. 

Perhaps we need a long name and a short name? short name is what we've got, long name is "author-year-languagegroup"? that could be generated with a slug function.

**Comment by xrotwang** [comment]
I think we can ignore namespace clashes on PyPI - although we have to take care not to clash with any package which could reasonably be installed in a user's lexibank environment. I actually prefixed all package names by `lexibank_`, so this should be ok.

**Comment by LinguList** [comment]
I'd say, as long as I may change a name I find unuseful before official releases, I'd be fine with the policy...

**Comment by xrotwang** [comment]
So, overall, we'd go for naming the dataset 
- after the publication or
- using an already established name

right?

If so, @LinguList wouldn't we want to keep the year in the name? This would also be a first mnemonic clue that the (raw) data is not supposed to change, whereas datasets like `asjp` or `abvd` may provide different states of the raw data in different releases.

**Comment by LinguList** [comment]
If we go for year and name: yes, but if we follow our earlier policy of catchy names, having a year in kraft1981 (and no mentioning of "chadic") vs. baidial seems inconsistent, or makes it difficult to memorize dataset names, right?

**Comment by xrotwang** [comment]
Ok, so the above is just a recommendation, then. And the actual policy is: Whoever is the main contributor of a dataset can decide on the most useful name with regards to mnemonic quality (within our rules for syntax)? Consistency between dataset names would be only a second thought in this scenario. I think that's pragmatic and the most future-proof way of going about it. It's also the simplest rule to follow in case we actually get external contributions.

And as said before, in the worst case (i.e. dataset names becoming embarrassingly inconsistent) we'd have to make sure these names are mostly made invisible by appropriate tools.

**Comment by xrotwang** [comment]
So, while I'm at re-arranging the datasets, could - whoever feels responsible - let me know of any name changes (in particular of the 15 CLICS datasets)?

**Comment by xrotwang** [comment]
Candidates for change are probably `bowernpny`, `huberandreed` and `sunzmyyc`.

**Comment by LinguList** [comment]
here are my suggestions:

kraft1981 -> kraftchadic
huberandreed -> hubercolumbian (or huberreed)
satterthwaitephillipstb -> satterthwaitetb
sunzmyyz -> suntb
baidial -> allenbai
tryonhackmann -> tryonsolomon

if we say: year is not important but more author and language family...

**Comment by LinguList** [comment]
beidacihui -> beidasinitic

**Comment by LinguList** [comment]
or going with years but no family indicators, compare attached image from our clics paper:
![screenshot_2018-04-12_11-05-37](https://user-images.githubusercontent.com/2916210/38667324-7157aac8-3e41-11e8-9a10-36c6d1a3b8bc.png)

**Comment by tresoldi** [comment]
As long as we can automatically build a table such as this and put it in Lexibank's README.md, I think we are covered. Authors are properly cited, the range is there, and one can just copy & paste the dataset name. We might even link to the original paper/book/study, as the URLs (if any) are already in the metadata.

So, I'd say: let's give some guidelines as three or four bullet-points and trust the main contributor for each dataset to properly name their baby.

BTW, part of the burden of complex names could be lifted by making sure `lexibank`, the tool, correctly performs tab-expansion. I see that `readline.parse_and_bind("tab: complete")` is already in the code, we might take a look later, @xrotwang .

**Comment by xrotwang** [comment]
Yes, I have to adapt the tab-completion to use the list of registered entry points for completion. But that may alleviate the problem of hard-to-type names.

**Comment by SimonGreenhill** [comment]
Done this morning!
