### ISSUE TITLE
COBL example conversion to LexiBank

### ISSUE THREAD

**Issue by chrzyki** [lexibank/lexibank#100]
_From @LinguList on October 5, 2017 9:15_

A recent project on kinship terms in IE languages (lead by Fiona Jordan) needs some good IE data to test automatic cognate detection to infer sound change patterns to be able to use these to measure kin ship term cognacy. I am trying to provide help with LexStat analyses, and I figured, it would be a good example for COBL in CLDF/lexibank if we convert the cobl languages they were asking for to cldf and help them out. Needless to say: nothing will be published without our consent, only AFTER the COBL-paper is out. The steps involve:

- [ ] concepticon mapping of the 180 concept list (or maybe even more?)
- [ ] orthography profiles (using the new lingpy API
- [ ] glottocode identification (hopefully trivial)
- [ ] writing __init__ script for lexibank

Here's the list of glottocodes:

[kin-terms-languages.txt](https://github.com/glottobank/lexibank-data/files/1358692/kin-terms-languages.txt)

_Copied from original issue: glottobank/lexibank-data#338_

**Comment by SimonGreenhill** [comment]
This can be closed now, right.
