### ISSUE TITLE
Dataset: color terms in 190 Pama-Nyungan languages

### ISSUE THREAD

**Issue by chrzyki** [lexibank/lexibank#101]
_From @SimonGreenhill on October 7, 2017 7:32_

https://zenodo.org/record/1003137 

Single excel file, colored annotations. Probably is contained within the Chirila dataset.

_Copied from original issue: glottobank/lexibank-data#339_

**Comment by chrzyki** [comment]
_From @chirila on October 8, 2017 23:6_

It's mostly contained within Chirila but has additions which aren't in the
main db at present. I'm planning on adding the entirety of those sources.
C

**Comment by chrzyki** [comment]
_From @SimonGreenhill on March 2, 2018 7:57_

And while we're at it, we can get David Nash's alterations too: https://zenodo.org/record/1032450

**Comment by SimonGreenhill** [comment]
Done:
https://github.com/lexibank/nashcolorterms
https://github.com/lexibank/hayniecolorterms
