### ISSUE TITLE
Khobwa-Dataset with Cognate coding in almost perfect IPA

### ISSUE THREAD

**Issue by chrzyki** [lexibank/lexibank#104]
_From @LinguList on January 18, 2018 6:35_

Direct link to the supplement:

* https://cloudfront.escholarship.org/dist/prd/content/qt4t27h5fg/supp/dataset_khobwa.csv

Languages should be straightforward to link, there are 100 concepts, not clear which (will post separate issue to Concepticon).

_Copied from original issue: glottobank/lexibank-data#358_

**Comment by SimonGreenhill** [comment]
is this https://github.com/lexibank/bodtkhobwa?

**Comment by chrzyki** [comment]
That's the one: https://github.com/lexibank/lieberherrkhobwa
