### ISSUE TITLE
Dataset: Computational Phylogenetics and the Internal Structure of Pama-Nyungan

### ISSUE THREAD

**Issue by chrzyki** [lexibank/lexibank#108]
_From @SimonGreenhill on March 2, 2018 8:5_

Dataset of cognate judgements on which Bowern and Atkinson (2012) was based. Note that this dataset has been largely superseded by subsequent work which adds more languages and forms.

https://zenodo.org/record/1005671

_Copied from original issue: glottobank/lexibank-data#365_

**Comment by SimonGreenhill** [comment]
Done in https://github.com/lexibank/bowernpny
