### ISSUE TITLE
Dataset: Dravidian - Kolipakam et al.

### ISSUE THREAD

**Issue by chrzyki** [lexibank/lexibank#110]
_From @SimonGreenhill on March 21, 2018 8:14_

20 Dravidian languages, 100 words, with cognates: http://dx.doi.org/10.1098/rsos.171504

In CLDF: https://zenodo.org/record/1181715

_Copied from original issue: glottobank/lexibank-data#368_

**Comment by SimonGreenhill** [comment]
Done in https://github.com/lexibank/dravlex/
