### ISSUE TITLE
Standardise concepticon id and concepticon gloss in CLDF.

### ISSUE THREAD

**Issue by chrzyki** [lexibank/lexibank#112]
_From @SimonGreenhill on April 5, 2018 9:54_

I've just created a [PR here](https://github.com/glottobank/lexibank-data/pull/370) as the CLDF generated for Chapacuran did not include the concepticon_gloss data (the column was empty but the wordlist is fully defined in concepticon). 

I know we don't really need the glosses but each CLDF should be self-contained.

This could make a good automated check.

_Copied from original issue: glottobank/lexibank-data#371_

**Comment by SimonGreenhill** [comment]
We also have both (Concepticon_ID, Concepticon_Gloss) and (conceptset, concepticon_gloss) used in datasets e.g. 
* https://github.com/lexibank/robinsonap/blob/master/cldf/parameters.csv
* https://github.com/lexibank/kitchensemitic/blob/master/cldf/parameters.csv

Is there a preferred one?

**Comment by SimonGreenhill** [comment]
(Tagging @xrotwang and @chrzyki now, sorry, as better to decide on this sooner rather than later).

**Comment by xrotwang** [comment]
True. Should be made consistent (and should be an issue in lexibank/pylexibank :grinning:  )

**Comment by SimonGreenhill** [comment]
Moved https://github.com/lexibank/pylexibank/issues/19 :)
