### ISSUE TITLE
Dataset: McElhanon 1970 Huon Peninsula

### ISSUE THREAD

**Issue by chrzyki** [lexibank/lexibank#113]
_From @SimonGreenhill on April 5, 2018 12:49_

as used by me in http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0141563

_Copied from original issue: glottobank/lexibank-data#373_

**Comment by SimonGreenhill** [comment]
Added here: https://github.com/lexibank/mcelhanonhuon
