### ISSUE TITLE
Dataset: Marrison et al

### ISSUE THREAD

**Issue by chrzyki** [lexibank/lexibank#114]
_From @MacyL on April 5, 2018 14:7_

source : Marrison, Geoffrey Edward. 1967. The classification of the Naga Languages of north-east India. Ph.D. Dissertation, School of Oriental and African Studies, University of London. 2 volumes. [from STEDT source]
content :  909 lexical items, 40 languages (including Naga_Chungli (Ao Naga population) and etc. ) 
work progress : it has a good coverage (above 800 concepts) with Concepticon database. (with Mattis' help) 
provide bibtex format 
  @phdthesis{marrison1967classification,
  title={The classification of the Naga languages of north-east India.},
  author={Marrison, Geoffrey Edward},
  year={1967},
  school={School of Oriental and African Studies (University of London)},
  note={Accessed via STEDT database}
}

_Copied from original issue: glottobank/lexibank-data#374_

**Comment by chrzyki** [comment]
_From @LinguList on April 5, 2018 14:9_

rather biggish dataset, nice for CLICS and other projects, here are the steps to add it:

- [x] concepticon mapping (@MacyL currently on it)
- [ ] orthography profile (at least a rudimentary one)
- [ ] check glottocodes of the languages (they have ISO codes, so using glottolog api, they can be easily found)
- [ ] write lexibank `__init__` script

**Comment by chrzyki** [comment]
_From @tresoldi on April 5, 2018 14:13_

I've been through all of this and wrote a little guide here: https://github.com/glottobank/lexibank-data/blob/master/cookbook/new_dataset_walkthrough.md (maybe Mattis already pointed you to that?)

If I can be of any help, just tell me and I'll take my three or four steps to get there. ;)

**Comment by chrzyki** [comment]
_From @LinguList on April 5, 2018 14:17_

I completely forgot (sorry). I suppose, we run @MacyL this time through concepticon mapping, and make a code review on github.

**Comment by SimonGreenhill** [comment]
Here: https://github.com/lexibank/marrisonnaga
