### ISSUE TITLE
Remove README.json

### ISSUE THREAD

**Issue by xrotwang** [lexibank/lexibank#115]
The info we currently put in a dataset's `README.json` doesn't have any clear use case yet - it was supposed to be the machine readable variant of `README.md`. But given that
- this information should correspond to the data in `cldf/`
- the CLDF dataset does already provides some information for cataloging (see https://www.w3.org/TR/vocab-dcat/)

we should simply put useful summary statistics into the CLDF dataset description and drop `README.json`.

**Comment by SimonGreenhill** [comment]
Important to distinguish between lexibank and CLDF here. It makes sense to have numbers of {languages, parameters, cognates, etc} in CLDF (i.e. nrows for each table) in metadata.json.

In lexibank, however we're kind of using the badges as a statistics system, so we could continue adding this info to README.md as more badges or as formatted text. This has the benefit of being easily available and human readable but would need (possibly) complicated parsing to extract. 

We'd also thought about adding other info to this e.g.  #47 and #14, which would be awesome for lexibank but probably outside CLDF's scope. lexibank does have transcription.json. Perhaps we could rename this to lexibank.json and include the transcription report in there, along with anything else ?

**Comment by xrotwang** [comment]
I agree that not all of this would be useful for CLDF in general - but then, the CLDF description is a JSON-LD document, so adding namespaced info is easy and expected. It also seems natural to have descriptions of the CLDF data in the CLDF description :)

Regarding stuff like "minimal prosodic templates", I'd still say this could be useful for all CLDF Wordlist data, so the algorithm should eventually go into the CLDF cookbook.

**Comment by xrotwang** [comment]
I think I'm aiming at something like [dc:extent](http://dublincore.org/documents/dcmi-terms/#terms-extent), with a JSON dictionary as value
```python
"dc:extent"; {"lexibank:languages": 4, "lexibank:concepts": 4, ...}
```

**Comment by xrotwang** [comment]
This may also highlight why JSON-LD is a good choice for CLDF.

**Comment by SimonGreenhill** [comment]
+1 from me. Anyone else?

**Comment by tresoldi** [comment]
+1 from me, too.

**Comment by chrzyki** [comment]
Sounds very reasonable! 👍
