### ISSUE TITLE
Issue clean-up

### ISSUE THREAD

**Issue by chrzyki** [lexibank/lexibank#119]
As all of you will undoubtedly have noticed, we've moved all the issues from the old repository to this new one. Since that's quite a hefty package and baggage, I'd be curious to clean-up a little bit of that. Is that even feasible? Do I have the background to do that? If so, what would be a good starting point?

**Comment by LinguList** [comment]
simple things, like consistency checks on titles of issues are definitely straightforward. Identifying orphaned issues probably too, AND it will help you to see the different stages we worked on this, so I think that it may be useful to go ahead and also be bold and just mark things as outdated or close issues right away if the discussions are no longer relevant...

**Comment by SimonGreenhill** [comment]
agree with @LinguList -- we can reopen if needed. There's lots of things that should be easy to fix and close e.g. https://github.com/lexibank/lexibank/issues/22

**Comment by chrzyki** [comment]
Neat, awesome, thank you both! I'll have a go at this.
