### ISSUE TITLE
Dataset: Kongo languages (92 concepts)

### ISSUE THREAD

**Issue by chrzyki** [lexibank/lexibank#12]
_From @LinguList on July 28, 2016 10:40_

So far, they haven't uploaded the supplementary material, but in the paper, they announce that it will be put online:
- http://poj.peeters-leuven.be/content.php?url=article&id=3122579&journal_code=AL

The data contains some 92 words and a larger set of languages. I expect it to be similar to the Grollemund-data, since it's the same author-team (at least in parts).

_Copied from original issue: glottobank/lexibank-data#20_

**Comment by chrzyki** [comment]
_From @xrotwang on January 27, 2017 11:11_

Any news regarding the data?

**Comment by chrzyki** [comment]
_From @LinguList on September 4, 2017 17:43_

Data has now been found, we just need to decide: do we put it in lexibank as is, do we put it on zenodo first, maybe asking our friend K.B., or do we wait until the journal officially publishes the data (could be never)?

**Comment by chrzyki** [comment]
_From @LinguList on January 31, 2018 9:20_

supplementary material now appeared finally online: http://www.africamuseum.be/research/publications/rmca/journals/alvol21

**Comment by LinguList** [comment]
This is the same as #151
