### ISSUE TITLE
Dataset: Bacovcin and Wilson (2018): Afro-Asiatic languages

### ISSUE THREAD

**Issue by LinguList** [lexibank/lexibank#120]
Code and data for this interesting paper are shared on github:

* https://github.com/bacovcin/minimum-homoplasy

Data also contains the Austro-Asiatic dataset (raw folder) they describe in the paper ([DOI](http://dx.doi.org/10.1111/1467-968X.12128)).

Thanks to Hezekia Akiva Bacovcin for pointing to the repository.

**Comment by LinguList** [comment]
Update: it seems this dataset file [here](https://github.com/bacovcin/minimum-homoplasy/blob/master/rawdata/AA/AA-Attested-15050.csv) only contains the states, not the words. The question is: is it still worthwhile converting this to CLDF to prove a point? Can we even do that? Convert to CLDF, show that cognate sets also work with dummy words, so people can at least use the nexus created?

**Comment by xrotwang** [comment]
No, it would still be a Wordlist - just one with empty forms. I think, so far, this would be illegal, so one would have to supply dummy forms of some sort.

**Comment by xrotwang** [comment]
Whether this would be worthwhile, I don't know. It would just mean that you can shoehorn any kind of language-concept matrix into the Cognates table ...

**Comment by SimonGreenhill** [comment]
...which could be useful?

Rather than a dummy entry, could we just use a "missing item" token? e.g. "-"?

**Comment by LinguList** [comment]
This is in fact a structure dataset in our new terms.
