### ISSUE TITLE
Fork our tutorial cldf data as an example for lexibank integration of foreign sources

### ISSUE THREAD

**Issue by LinguList** [lexibank/lexibank#124]
Should be straightforward, right? The data is already in cldf, or do we have to go through the install process in order to make it available?

Okay: we lack things like glottocode, etc. 

So rather add a lexibank repo on this paper?

**Comment by xrotwang** [comment]
Sorry, which dataset is this about? The one for the lingpy tutorial?

**Comment by LinguList** [comment]
Yes, the file polyensian.tsv. https://github.com/lingpy/lingpy-tutorial

**Comment by LinguList** [comment]
In fact: the reason why glottocodes are NOT written to cldf is not that they aren't there, but that our function to convert to cldf doesn't recognize them in lingpy's redundant one-file format.

**Comment by LinguList** [comment]
I think: since quite a few people work on edictor/lingpy now, we should add the functionality to write languages from within lingpy's conversion function. Ideally, lingpy would always keep up with cldf and offer an equivalent form in this redundant way of placing things in additional columns.

**Comment by xrotwang** [comment]
Sounds like candidate functionality for `lexibank-util` - bridging lexibank and edictor/lingpy.

**Comment by xrotwang** [comment]
The main functionality I see lexibank providing over CLDF is merging datasets. So I guess for edictor and lingpy - which are specializing in lexical data, thus don't need to support the generality of CLDF - it would be natural to sit on top of lexibank.

**Comment by SimonGreenhill** [comment]
Is this still valid?
