### ISSUE TITLE
[new dataset] wiktionary appendix on Kho-Bwa

### ISSUE THREAD

**Issue by LinguList** [lexibank/lexibank#128]
* https://en.wiktionary.org/wiki/Appendix:Kho-Bwa_comparative_vocabulary_lists#Abraham,_et_al._(2018)

This is interesting, as it is the data by this Abraham et al. 2018, so it is accessible via wiktionary. And they have some more longer lists in this form typed off, it seems. In fact, quite easy to add to lexibank, right? Might even worth to add a customized system, for a provider, as I assume that these tables can be found in a regular way? Otherwise: copying from the debugger in firefox via "copy internal node" and pasting to excel should also do the trick.

**Comment by tresoldi** [comment]
I was playing with that when I was extracting my Wiktionary data. In the case of Swadesh lists there, most tables (basically everything which does not come from a well-documented languages, such as English or Spanish) come from a handful of users, and the SEA languages are almost all from user `Steve7788`, which I am not sure would contribute them (he/she is not bound to, of course: https://en.wiktionary.org/wiki/User_talk:Stevey7788)

But copying the data is easy: one can just list the articles where they are found and process the raw data served at wikimedia.org. You can see it is markdown-like and easy to parse:

[source](https://en.wiktionary.org/w/index.php?title=Appendix:Kho-Bwa_comparative_vocabulary_lists&action=edit)

```
{| class="wikitable sortable"
! # !! Gloss !! Chugpa (Duhumbi) !! Lishpa (Khispi) !! Sherdukpen (Rupa) !! Sherdukpen (Shergaon) !! Sartang (Rahung) !! Sartang (Khoitam) !! Sartang (Jerigaon) !! Sartang (Khoina) !! Bugun (Dikhyang) !! Bugun (Singchung) !! Bugun (Wangho) !! Bugun (Bichom) !! Bugun (Kaspi) !! Bugun (Namphri) !! Puroik (Bulu) !! Puroik (Kojo Rojo) !! Puroik (Rawa) !! Puroik (Saria) !! Puroik (Chayangtajo) !! Puroik (Lasumpatte) !! Puroik (ZMYYC 1991) !! Puroik (Li Daqin 2004)
|-
| 45 || 1SG || ga  || ga  || gu || gu || gu || gu || gu || gu || koː || go || ko || go ~ gu || gu || go || gu || go || go || go || go || go || goh⁵³ || goh⁵⁵
|-
| 100 || 2SG || naŋ  || naŋ  || naŋ  || naŋ  || naŋ  || naŋ  || naŋ  || naŋ  || nɔ̃ || no || no || no || no || no || naː || naŋ || na || na || na || na || nah⁵³ || na⁵⁵
```

**Comment by LinguList** [comment]
BTW: https://en.wiktionary.org/wiki/Appendix:List_of_Proto-Lalo_reconstructions 

This would have been the easier way, I guess...

**Comment by LinguList** [comment]
This dataset should be handled along with the datasets #130, as it is the same source, containing some 20+ languages.
