### ISSUE TITLE
Sources: detailed sources for Wheeler-2015 dataset (wwua)

### ISSUE THREAD

**Issue by chrzyki** [lexibank/lexibank#15]
_From @LinguList on July 29, 2016 11:13_

They list very detailed sources and more in an accompanying PDF
- [sources.pdf.zip](https://github.com/glottobank/lexibank-data/files/390399/sources.pdf.zip)

Ideally, we would add them to the dataset. But this work can hardly be done by us and is probably better to be delegated to student assistants (as are other tasks concerning language mapping, etc.). 

_Copied from original issue: glottobank/lexibank-data#28_

**Comment by chrzyki** [comment]
_From @LinguList on August 29, 2016 6:43_

Just figured, that we could, for the moment, live with the following sources:
- Wick Miller’s Uto-Aztecan Cognate Sets, Revised and Expanded by Kenneth C. Hill, May, 2011

This is a manuscript which was given to Wheeler et al. to be used.

**Comment by tresoldi** [comment]
Dataset also available here https://wardwheeler.wordpress.com/data-sets/

**Comment by SimonGreenhill** [comment]
Fixed
