### ISSUE TITLE
Provide style guides describing a "good" Lexibank dataset

### ISSUE THREAD

**Issue by xrotwang** [lexibank/lexibank#156]
Most of this could still fit into this repos' `README.md`, maybe at some point we might have to break this into multiple docs, though.

**Comment by SimonGreenhill** [comment]
Add anything you can think of to this list and we can debate the merits.

[ ] All languages.csv should have Latitude, Longitude filled in (?)
[ ] All parameters.csv should have both Concepticon_ID and Concepticon_Gloss filled in
[ ] Thou shalt run `lexibank check mydataset` and fix all errors.

**Comment by LinguList** [comment]
We should definitely discuss how to either enhance or describe the process of making orthoprofiles. I am almost happy with my current workflow, and I think my javascript implementation of the code [here](http://calc.digling.org/profile) should also help a lot. Not to forget about [orthograpy](https://github.com/cldf/orthograpy), which is also growing. But it is not necessarily clear to everybody, so we need to discuss how to enhance things here.

**Comment by chrzyki** [comment]
> [ ] Thou shalt make sure you have the most up-to-date glottolog
> [ ] Thou shalt make sure you have the most up-to-date concepticon

Should this be the `master` branch of the respective catalog or the stable release of Concepticon and Glottolog?

**Comment by LinguList** [comment]
Here's what I think so far:

1. Think of a good and short title for your dataset, provided it in capitalized form
2. Think of a good identifier for your dataset, which should be in lowercase, and only alphanumeric
3. If you provide an orthography profile, make sure your IPA column conforms to CLTS
4. When checking your orthography profile, make sure there are no errors in the conversion. If you find errors you cannot correct, provide an empty symbol, by using the `source/target` construct
5. Do not provide data that could be computed, e.g., automated alignments or cognates. As we can compute them anytime ourselves, we prefer to only share those datapoints in lexibank that have been manually checked
6. If you deal with dialects and link several varieties to the same glottocode, consider providing locations with your dataset
7. Consider submitting your concept list to concepticon, if it is published
8. Use clearcut quotation suggestions for your dataset, give us a publisher (e.g., your current department or insitute) and a location (where you work), note that datasets with a publisher and a location are quoted more frequently
9. Be clear about the contributors. Be fair in listing those who helped to create your data.
10. Tell us a bit more about your data in the note.md field, so we know how it was produced and what it could be used for.

**Comment by xrotwang** [comment]
Some of these recommendations apply only to datasets curated with
pylexibank. I'd move these to the pylexibank repos.

Johann-Mattis List <notifications@github.com> schrieb am Do., 11. Juli
2019, 15:23:

**Comment by xrotwang** [comment]
Re publishers: wouldn't Zenodo function as publisher of lexibank datasets?

Robert Forkel <xrotwang@googlemail.com> schrieb am Do., 11. Juli 2019,
15:31:

**Comment by LinguList** [comment]
perfect, yes, of course! One could even use the Cern's location then! I mean, nobody cares who's the publisher, but it is just so important for making a publication "real"...

**Comment by SimonGreenhill** [comment]
Do we have a way of getting the concept list from concepticon? I looked through some datasets, but most seem to be duplicating concepts.tsv from concepticon which is non-optimal.

**Comment by LinguList** [comment]
Depends on production stage. `chenhmongmien`, for example, was preliminarily mapped, but not translated, so @MacyL translates it now, I'll double-check, and we can release this with concepticon later. But often, one only realizes how interesting this is, before one starts already submitting it to concepticon, plus there are cases where the data is in fact different from the official concept list. And we had those issues in the past. See e.g., `halenepal`. So what is ideal on first sight may be problematic in practice. But there should be the ambition to concepticonify concepts.tsv wherever possible.

**Comment by SimonGreenhill** [comment]
Got this in here: https://github.com/lexibank/lexibank/blob/master/CONTRIBUTING.md

**Comment by SimonGreenhill** [comment]
(please add specific suggestions directly to https://github.com/lexibank/lexibank/blob/master/CONTRIBUTING.md_
