### ISSUE TITLE
[new dataset] walworthpolynesian

### ISSUE THREAD

**Issue by LinguList** [lexibank/lexibank#165]
https://zenodo.org/record/1252231 

@schweikhard will help adding this. @chrzyki, can you give him access, or help creating a first empty repo?

**Comment by chrzyki** [comment]
Yupp, will do.

**Comment by chrzyki** [comment]
Done here https://github.com/lexibank/walworthpolynesian and write invite sent.

**Comment by Schweikhard** [comment]
Thanks!
