### ISSUE TITLE
Joo Ian's Master Thesis: excellent wordwide sample of wordlists

### ISSUE THREAD

**Issue by LinguList** [lexibank/lexibank#177]
https://github.com/ianjoo/LJ-List

One may not even need an orthoprofile here.

**Comment by LinguList** [comment]
He just told me: the paper on the thesis will be published next week in linguistic typology. Another good point to cldfify it, even if it would even be better if that happened before...

**Comment by LinguList** [comment]
see [lexibank/joophonosemantic](https://github.com/lexibank/joophonosemantic) for a first version (sources missing).

**Comment by chrzyki** [comment]
https://github.com/lexibank/joophonosemantic
