### ISSUE TITLE
Kim Mun in Lao and Vietnam by Eddie Clark

### ISSUE THREAD

**Issue by MacyL** [lexibank/lexibank#196]
I found this master thesis online : 
Clark, Eddie. (2008). A phonological analysis and comparison of two Kim Mun varieties in Laos and Vietnam (Master's thesis). Payap University.

Kim Mun (Lao ) 503 item
Kim Mun (Vietnam) 441 item

**Comment by LinguList** [comment]
nice.

**Comment by MacyL** [comment]
I am working on this dataset, so I will close this issue.
