### ISSUE TITLE
Migrating the Google sheet to GitHub Projects

### ISSUE THREAD

**Issue by chrzyki** [lexibank/lexibank#198]
We have the Google sheet with a lot of helpful information. However, since the information are somewhat detached from GitHub I find myself checking this not as often as I should, particularly with the upcoming sprint towards more/improved/better datasets.

I've been wondering what your opinion would be on trying to transfer as much of the sheet's information as possible to a larger GitHub project e.g. in this repository? I'd hope that this would make assigning responsibilities easier and give us a more direct and better overview of things that would need to be done for certain datasets.

What do you think? If you're not totally against this, I could try and come up with a workflow around GitHub projects, transferring as much as possible from the sheet in the process and integrate it here with GitHub.

**Comment by xrotwang** [comment]
I think the major benefit of the Google doc was overview over **all**
datasets. If this is possible with a github project, the tighter
integration of task and resolution would be welcome.

Christoph Rzymski <notifications@github.com> schrieb am Sa., 1. Feb. 2020,
08:08:

**Comment by tresoldi** [comment]
I agree with @xrotwang . But what kind of workflow do you have in mind? The information on Google Sheets could be just a csv or md file, which we can make sure is rendered correctly by GitHub. I suppose I am missing something?

**Comment by chrzyki** [comment]
https://github.com/lexibank/lexibank/projects to properly assign issues, responsibilities, and manage priorities. Ideally (partially) filled with the information from the respective repositories.

**Comment by LinguList** [comment]
For me, personally, it was easy to set the sheet up, as it helped me to check what we have, etc., and is easy to edit. I agree with any alternative solution, as long as tables there are editable as csv files. So please no markdown tables.

Project boards is something we tried, but github is slow, it is a pain in the neck to work with them, so in the end, everybody stopped using them in our calc project, so I am against testing this now, based on my bad experience with them in the past.

**Comment by chrzyki** [comment]
I'll see whether I can find a way to continue using the lexibank project (https://github.com/orgs/lexibank/projects/1) and keep the sheet updated.

**Comment by SimonGreenhill** [comment]
Hi all, I also would like tighter integration, but github is kind of annoying. I have been keeping the project board relatively updated, so maybe that will help?

**Comment by SimonGreenhill** [comment]
(but I do agree with @LinguList that it's non-optimal. Personally, I'd just like one long list of issues for all the repos in this organisation)

**Comment by tresoldi** [comment]
It would technically be possible to automate this, also by relying on GitHub APIs, but I wonder a) how much this is worth the trouble, especially considering that it would be one extra software to maintain and b) if it would not start to entangle the workflow too much to GitHub.
