### ISSUE TITLE
Dataset: Sattherthwaite-Phillips' Sino-Tibetan Database

### ISSUE THREAD

**Issue by chrzyki** [lexibank/lexibank#22]
_From @LinguList on August 29, 2016 8:49_

- https://purl.stanford.edu/wv919xj7158

Data comprises a rather large wordlist of about 20 languages in Sino-Tibetan, mostly phonetically encoded.

The author also gave me the excel spreadsheet, so it's easier to parse the data, and the list is in Concepticon as 
- http://concepticon.clld.org/contributions/SatterthwaitePhillips-2011-423

It is a CC3-non-commercial license. When adding it, we should add Damian to the list of thanked people in the acknos.

Only for the mnemonic identifier, I'm not very sure. satterthwaitephillipssinotibetan is a bit long...

_Copied from original issue: glottobank/lexibank-data#56_

**Comment by chrzyki** [comment]
_From @xrotwang on August 29, 2016 9:9_

I guess `satterthwaitephillips` would be ok.

**Comment by chrzyki** [comment]
_From @LinguList on September 20, 2016 8:3_

Adding this, we should put Damian Sattherthwaite-Phillips on the contributors' list, as he provided the data to me via email.

**Comment by SimonGreenhill** [comment]
@xrotwang -- this is a good example for the CONTRIBUTORS.md (the author provided the raw data).
