### ISSUE TITLE
FAQ/Cookbook on how to add datasets

### ISSUE THREAD

**Issue by chrzyki** [lexibank/lexibank#25]
_From @LinguList on September 4, 2016 12:48_

I was recently sending off a few emails to people for potential contributions. It would be good to have some standard text, potentially in PDF, that we could attach, something like a FAQ, so that people don't get scared, and that we don't need to write too much when asking, but can then still be personal in the email, yet append the FAQ as pdf. I'd suggest we can collect most important questions in this thread.

_Copied from original issue: glottobank/lexibank-data#66_

**Comment by SimonGreenhill** [comment]
I think a cookbook on "how to add" a dataset is a better option than a PDF FAQ.

**Comment by thiagochacon** [comment]
yes, on the contributor side, that would be quite helpful indeed! A step by step explanation would be great.

**Comment by tresoldi** [comment]
A starting point could be the guide I wrote back in December: https://github.com/glottobank/lexibank-data/blob/master/cookbook/new_dataset_walkthrough.md

I could take the time to update it to the new architecture if you think it would be worth.

**Comment by xrotwang** [comment]
@tresoldi yes! Porting this guide to the new architecture and putting it in lexibank/pylexibank/cookbook would be nice!

**Comment by LinguList** [comment]
There are two points: 

1. having users contribute a dataset, and
2. explaining to other people what lexibank is and what happens with their data

My FAQ was addressing the 2nd point. Definitely, we need to address point 1, but point 2 is important, as I am often asking people for data, and write half-page-long emails to explain the project. A standardized form there would be helpful that is still personal enough, but where I can just point to the lexibank project. We could then also divide who's contacting whom, or use some shared address from lexibank@shh.mpg.de to contact people officially.

**Comment by LinguList** [comment]
So as these are two issues, I moved the original issue here: #123

**Comment by xrotwang** [comment]
@LinguList at least technically, I think point 2 is somewhat addressed now in https://github.com/glottobank/lexibank/blob/master/README.md where I added a bit of explanation of the GitHub org and the ZENODO community.

But I agree, some standard wording may be good. OTOH, when it comes to asking people to put a license on their data, standard wording may often fail.

**Comment by xrotwang** [comment]
Btw.: I accidentally linked to the README in glottbank/lexibank above. Maybe that's a sign that we should eventually delete this obsolete repository?

**Comment by tresoldi** [comment]
Yes to delete from GitHub, but let's keep all the documentation we can (`/cookbook` in particular).

**Comment by xrotwang** [comment]
@tresoldi haha, that's yet another repository you are talking about: glottobank/lexibank-data :)

**Comment by SimonGreenhill** [comment]
yes, lets cull glottobank/lexibank. Have we extracted all the datasets (we should keep everything that's not clics private for now)

**Comment by xrotwang** [comment]
The only dataset in https://github.com/glottobank/lexibank/tree/master/datasets I don't see in current lexibank is [McElhanon1967](https://github.com/glottobank/lexibank/tree/master/datasets/McElhanon1967). @LinguList do we have to keep this one file?

**Comment by LinguList** [comment]
Maybe not, but it's an example of how TNG data can be lexibankified (if somebody works on it). And the data is segmented.

**Comment by SimonGreenhill** [comment]
it's one of mine, and I've published a paper with it so should release it properly. I've saved that file and add it as a new dataset when I get a chance. Feel free to delete it now.

**Comment by xrotwang** [comment]
ok

**Comment by xrotwang** [comment]
it's gone. I cloned repos and wiki and downloaded the one remaining open issue.

**Comment by SimonGreenhill** [comment]
Closed in favor of https://github.com/lexibank/pylexibank/issues/43
