### ISSUE TITLE
Dataset: Walker and Riberio Arawakan data

### ISSUE THREAD

**Issue by chrzyki** [lexibank/lexibank#28]
_From @SimonGreenhill on September 21, 2016 11:57_

http://rspb.royalsocietypublishing.org/content/278/1718/2562.long

_Copied from original issue: glottobank/lexibank-data#85_

**Comment by chrzyki** [comment]
_From @LinguList on December 5, 2016 7:55_

Do we have the data?

**Comment by chrzyki** [comment]
_From @SimonGreenhill on December 5, 2016 9:6_

Hmm. An interesting case. The data used to be available on the lead authors website. This site has now changed, and it's no longer on that. 

I saved a copy a long time ago, but it's a word doc, with lots of weird webdings glyphs in it (could be because I'm using a mac): 

![walker](https://cloud.githubusercontent.com/assets/220169/20879109/725ce422-bad2-11e6-827d-29d32db47d1b.png)

So perhaps more trouble than it's worth? Reopen if you disagree.

**Comment by chrzyki** [comment]
_From @LinguList on December 5, 2016 9:31_

well, we could still ask them, if the data seems to be interesting
enough. @xrotwang showed that doc may be handled straightforwardly, but
I'd say: no direct priority for the moment.

**Comment by chrzyki** [comment]
_From @xrotwang on December 5, 2016 9:53_

Will be forgotten, if left closed, I guess. Also if we wanted to contact the authors, that should probably better be done now than later.

**Comment by chrzyki** [comment]
_From @LinguList on December 5, 2016 19:33_

Looks awful, the data, from the sketch, but contacting the authors might help, would also be interesting to see their original "Swadesh list".

**Comment by SimonGreenhill** [comment]
I've just had a email conversation with Robert Walker on this, the other author (Riberio) would have had the raw data but he passed away a few years ago, unfortunately. So, this is the best that can be had for these at the moment :/

**Comment by SimonGreenhill** [comment]
This might be a good job for a hiwi, the wordlists show which sources the raw data are from, so it should be a matter of giving a hiwi a list of problematic entries and they can go to the sources and figure out what the characters should be. (@chrzyki @LinguList)

<img width="1004" alt="Screen Shot 2019-04-16 at 16 28 42" src="https://user-images.githubusercontent.com/220169/56218145-ba4b3d80-6064-11e9-997b-a5c04afd6eb3.png">

**Comment by chrzyki** [comment]
Sounds like a good task, yes!

**Comment by chrzyki** [comment]
Would like to get Natalia started on this - any pointers, comments, wishes before we do that, @SimonGreenhill, @LinguList?

**Comment by SimonGreenhill** [comment]
(@LinguList  -- this is the dataset I mentioned to your this morning).

**Comment by LinguList** [comment]
Yes, as this is basically due to a specific font, and custom unicode characters, it is something that will work well in form of an orthoprofile, right? The task would be:

1. identify the original source (is this possible?, is there a book on this?)
2. if not: check with other sources on Arawakan
3. try to identify the unicode characters attached to a glyph (while writing orthoprofiles)
4. make the typical lexibank workflow

I'd say: this is worth a try, to look into with Natalia. We could show it to her and then have her decide if she wants to take this as her next project?

**Comment by SimonGreenhill** [comment]
Here's the data


[Walker_Ribeiro - 2011 - Bayesian phylogeography of the Arawak expansion in lowland South America.doc.zip](https://github.com/lexibank/lexibank/files/3106972/Walker_Ribeiro.-.2011.-.Bayesian.phylogeography.of.the.Arawak.expansion.in.lowland.South.America.doc.zip)


I'd recommend  pre-processing this into a CLDF/TSV file and then trying to translate the unknown glyphs (they seem to be distinct items in the private use range, so figuring out one of the lexemes should correct many).

**Comment by natalia-morozova** [comment]
I am on this issue. First, I have compiled the table of “broken phonetic inventory” for each of the lists. Assuming that consistent weird symbols throughout several lists represent the same phonemes, I came up with a minimum number of lists (15 out of 60) and sources for them, which would help to decode all the symbols (the languages are Amuesha, Apurinã, Bahuana, Baniva, Baniwa, Bare, Caquinte, Kurripaco, Inapari, Kinikinau, Resigaro, Wapixana, Guajiro, Yavitero, and Yawalapiti). I have already gone through the sources for Apurinã and found out that the problem occurred with IPA symbols (e.g. ɨ).

I managed to find almost all the sources for those 15 languages either at the MPI library (already checked out the books), ThULB, or online. However, I still need this book: **RAMIREZ, Henri. Línguas Arawak da Amazônia Setentrional: Comparação e descrição. EDUA, Manaus, 2001**. Would it be possible to order it? It is a great sources that covers many wordlists!

**Comment by SimonGreenhill** [comment]
Fantastic -- thanks Natalia. Yes, feel free to order it, ask the librarians.

**Comment by natalia-morozova** [comment]
Please find attached the files with the lexemes in 60 Arawakan languages, the English glosses mapped to Concepticon, the languages mapped to Glottolog, and the corrected symbols. 
To correct the glyphs, I used the available sources provided for each language. However, most of the original phonetic characters were substituted with IPA characters; I used the following online sources to determine the IPA symbols that could have been used by Walker and Ribeiro: <http://www2.unucseh.ueg.br/gicli/ListasEnglish.htm>, <https://ids.clld.org/>, and <http://linguistics.berkeley.edu/~saphon/en/by-name.php>.

The 100-word Swadesh lists contain NAIL and CHILD instead of CLAW and PERSON.

[ARAWAKAN.zip](https://github.com/lexibank/lexibank/files/3217294/ARAWAKAN.zip)

**Comment by LinguList** [comment]
How cool! Who'll do a first pass with lexibank? If somebody makes the first forms.csv, e.g., @chrzyki, I can illustrate the usage of orthoprofiles then, and we can integrate it with the new command for pylexibank, to check orthoprofiles quickly...

**Comment by tresoldi** [comment]
There are still some comments in Portuguese and I am somewhat familiar with Arawak languages, I will take care of a first lexibank pass. I also met Ángel Mori (one of the authors) in Brazil, if there are some unsolvable doubts I can always write him.

**Comment by chrzyki** [comment]
Thanks @tresoldi  and thank you very much, @natalia-morozova, great job! I'd be eager to see this progress, particularly with respect to the orthography profiles (for me and for @natalia-morozova). Let us know when we can look over your shoulder. :)

**Comment by SimonGreenhill** [comment]
Great work @natalia-morozova!

**Comment by tresoldi** [comment]
I've just pushed a first version: 57 varieties, 5,725 lexemes. It is still missing an orthographic profile and needs some review in terms of language mapping, possibly including a PR to Glottolog itself.

@natalia-morozova and I will start working on the profile tomorrow and I will review the issues with languages today (two of them are currently explicitly excluded).

**Comment by tresoldi** [comment]
Forgot to link: https://github.com/lexibank/walkerarawakan

I am closing this issue and will open the new ones there.

**Comment by SimonGreenhill** [comment]
Great! thanks @tresoldi and @natalia-morozova
