### ISSUE TITLE
Dataset tests

### ISSUE THREAD

**Issue by xrotwang** [lexibank/lexibank#3]
I took a stab at implementing testing for datasets. It's fairly simple (I think):
- tests are run via pytest - like for all our other packages
- `pylexibank` installs a pytest plugin, providing fixtures like
  - `cldf_dataset`: the CLDF dataset
  - `<table>_schema`: a [Table Schema descriptor](https://frictionlessdata.io/specs/table-schema/#descriptor) to be passed into `goodtables.validate` as `schema`
  - `<table>_report`: the `goodtables` validation report for a table
- travis integration, see e.g. https://travis-ci.org/lexibank/allenbai/builds

The required test code can be minimal, I think, e.g. https://github.com/lexibank/allenbai/blob/master/tests/test_forms.py

**Comment by xrotwang** [comment]
@SimonGreenhill @tresoldi @chrzyki @LinguList does this look acceptable/sufficient?

**Comment by chrzyki** [comment]
Very cool! Any data set where I could try my hand at this? :)

**Comment by tresoldi** [comment]
This can actually go to a bullet-point list of "things that lexibank is great at: automatic tests for lexical databases.

**Comment by SimonGreenhill** [comment]
Does coverage work? would be good to identify code chunks that aren't tested.

**Comment by xrotwang** [comment]
@SimonGreenhill what code do you think should be tested? The code used in the pylexibank workflow? That's not really the purpose of the tests here, I think - or maybe they are implicitely tested, because the CLDF is their output?
My idea here is rather, that this setup would also be available to non-lexibank curated datasets.

**Comment by xrotwang** [comment]
I actually dropped test support using `goodtables`, since the trade-off wasn't particularly good:  `goodtables`
- comes with quite a few dependencies
- doesn't check referential integrity
- can't really do checks of the sort "there must be a record with these fields"

What it does well is making sure files are structurally valid CSV - but that's mostly implicitly tested when reading the files using `pycldf` as well.

**Comment by SimonGreenhill** [comment]
No, I just wanted a quick way to see which lines of code weren't being tested, but I guess if we test each CLDF table, then it's 100% covered be definition

**Comment by xrotwang** [comment]
I introduced an inconsistency in the `allenbai` dataset, and this what it looks like in travis:
https://travis-ci.org/lexibank/allenbai/jobs/368083582

Note the validation output following
```
----------------------------- Captured stderr call -----------------------------
```
```

**Comment by SimonGreenhill** [comment]
like this:

```
________________________________ test_contains _________________________________
cldf_dataset = <cldf:v1.0:Wordlist at cldf>, log = <Logger lexibank (WARNING)>
    def test_contains(cldf_dataset, log):
>       assert cldf_dataset.validate(log=log)
E       assert False
E        +  where False = <bound method Dataset.validate of <cldf:v1.0:Wordlist at cldf>>(log=<Logger lexibank (NOTSET)>)
E        +    where <bound method Dataset.validate of <cldf:v1.0:Wordlist at cldf>> = <cldf:v1.0:Wordlist at cldf>.validate
tests/test_forms.py:6: AssertionError
----------------------------- Captured stderr call -----------------------------
cldf/forms.csv:2 Key xallenbai-jianchuan not found in table languages.csv
=========================== 1 failed in 4.79 seconds ===========================
The command "pytest" exited with 1.
before_cache
```

**Comment by xrotwang** [comment]
see https://github.com/cldf/pytest-cldf

**Comment by SimonGreenhill** [comment]
this looks cool and makes me feel a lot safer, thanks @xrotwang!
