### ISSUE TITLE
Dataset: Hruschka-2015 data on Turkic languages

### ISSUE THREAD

**Issue by chrzyki** [lexibank/lexibank#30]
_From @LinguList on September 30, 2016 8:25_

This data is particular, but it may be an interesting case for the flexibility of lexibank, as it assembles etyma rather than concept-aligned cognates. So we have, similar to the bdpa-germanic data a dataset of words of potentially different meanings across languages, whose meaning is not necessarily known, but the data comes in aligned form, and we can link the reconstructed meaning to the concepticon.

Given that we decided to allow for datasets of this kind (which would also allow us to include interesting parts of sound comparisons, or more subsets form BDPA), we should probably decide to flag these datasets accordingly, as it is important to make clear that individual words do not necessarily mean the comparison concept.

_Copied from original issue: glottobank/lexibank-data#97_

**Comment by chrzyki** [comment]
_From @LinguList on September 4, 2017 17:46_

Question is: should I ask Dan Hruschka to put this on Zenodo, or should we put it there ourselves?

**Comment by chrzyki** [comment]
_From @QuentinAtkinson on September 4, 2017 19:10_

Dan supports open science initiatives. I think he’d do it if you asked him.

**Comment by chrzyki** [comment]
_From @LinguList on September 6, 2017 8:45_

Just contacted Dan, I actually have the data from him already, just need to ask confirmation.

**Comment by SimonGreenhill** [comment]
https://github.com/lexibank/hruschkaturkic
