### ISSUE TITLE
Types of Data: Tagging datasets

### ISSUE THREAD

**Issue by chrzyki** [lexibank/lexibank#31]
_From @LinguList on September 30, 2016 8:30_

I'd propose, given issue #97 that we start thinking of tagging datasets by some simple tags. I'm thinking of (but this is only preliminary and we need to discuss it further):
- etyma: means, one _etymon_ with reflexes in several languages, no strict meaning across all reflexes
- cognate sets: it's clear, but again, cognate sets does not require meaning identity
- lexicostatistic dataset: classical Swadesh-lists, _semantically aligned_
- alignments
- proto-forms

There are potentially more, and the tags I suggested are by no means consistent, but the fact that we have datasets like bdpa-germanic vs. Kitchensemitic shows that we need to have some tags to distinguish these

_Copied from original issue: glottobank/lexibank-data#98_

**Comment by chrzyki** [comment]
_From @xrotwang on November 9, 2016 9:45_

I think tags like "etyma" or "lexicostatistic" or "proto-forms" are useful. But we should avoid potentially redundant information like "cognate sets" or "alignments". The existence of these should be inferred from the data, no?

**Comment by chrzyki** [comment]
_From @xrotwang on November 9, 2016 9:47_

I'd propose we start out with a prose description for each dataset (like you did for the Concepticon concept lists), and distill useful tags from these descriptions and actual use cases - e.g. cases where the distinction between "etyma" and "lexicostatistic" becomes important.

**Comment by chrzyki** [comment]
_From @LinguList on November 9, 2016 9:56_

yep, I agree. BTW: we should think of fixing those column names. I'm being inconsequent myself, and other people are also inconsequent. So far, I use:
- segments for those things that are "clpa"-like or go into clpa-evalution
- cognacy for cognate sets
- alignment for alignments

But, for example, partial cognates, alignments reflecting partial cognates, etc. are not included here. Note that partial alignments and normal alignments are not the same, unless we infer normal cognates from partial cognates using the strict identity criterion. There are surely more things which will be used in a more regular fashion, and we should try to fix those names,  ideally officially in the code, or in CLDF.

**Comment by chrzyki** [comment]
_From @LinguList on November 9, 2016 9:59_

Good idea, regarding the prose description. One question only: writing this into the json-file is a bit tedious, and it would be easier to have a description.md, where we can use links, like we do in Concepticon, e.g., referencing a dataset, saying that this is the original one, and maybe also linking bibliographic entries to some official reference catalogue, as I do with evobib in Concepticon (but I'd also be fine linking to glottolog instead). The advantage is that we produce publication-like descriptions of data and do not really need to care of keeping a full bibliography.

**Comment by chrzyki** [comment]
_From @xrotwang on November 9, 2016 10:6_

Regarding the description: We already have the `NOTES.md` files incorporated in the workflow. So I guess the description should go into these.

**Comment by chrzyki** [comment]
_From @LinguList on November 9, 2016 10:7_

Yes, you are completely right! And I suppose from clld we can have similar functionality with the `[something](:ref:dataset)`, right?

**Comment by chrzyki** [comment]
_From @xrotwang on November 9, 2016 10:8_

You mean the web app could render the markdown as HTML? yes.

**Comment by chrzyki** [comment]
_From @LinguList on November 9, 2016 10:9_

more specifically: the :ref: inside the link would automatically translate this to the url needed, as we do with `[conceptlist](:ref:Swadesh-1952-200)`.

**Comment by chrzyki** [comment]
_From @xrotwang on November 9, 2016 10:12_

I wasn't aware of this. Are we doing this at http://concepticon.clld.org? For lexibank datasets I think this is not necessary, because we could use "real" relative links like

```
[other dataset](../<ds-id>/README.md)
```

upon import into the web app these could be rewritten to link to a dataset's page in the app.

**Comment by chrzyki** [comment]
_From @LinguList on November 9, 2016 10:15_

Also straightforward. And yes, we do it at concepticon.clld.org, this saved me a lot of time, I was also thinking of having another shortcut, like `[Anonymous (2000)](:bib:Anonymous2000)`, which would spare rewriting the links to the bibliography all the time. So far I spell those links out.

**Comment by chrzyki** [comment]
_From @SimonGreenhill on July 28, 2017 12:7_

(Removed some off-topic comments).

**Comment by SimonGreenhill** [comment]
See also https://github.com/glottobank/lexibank-data/issues/322

**Comment by SimonGreenhill** [comment]
Closing for now.
