### ISSUE TITLE
Dataset: Northern Pakistan Language Survey

### ISSUE THREAD

**Issue by chrzyki** [lexibank/lexibank#36]
_From @LinguList on October 26, 2016 11:38_

Interesting study:

```
SOCIOLINGUISTIC SURVEY OF
NORTHERN PAKISTAN
VOLUME 2
LANGUAGES OF NORTHERN AREAS
```

210 concepts, already posted as concepticon-issue (see [here](https://github.com/clld/concepticon-data/issues/225).

Different subgroups of varying size:
- Doomaki
- Shina
- Burushaki
- Balti

Each between 1 and 20 (?) languages. Data is digitizable, but fonts are old, so IPA needs to be retrieved by describing mappings from the ASCII-like charts to Unicode.

_Copied from original issue: glottobank/lexibank-data#108_

**Comment by SimonGreenhill** [comment]
Is this digitally available somewhere?

**Comment by LinguList** [comment]
Yes, but in PDF-form, so turning to word, then turning the word to excel or similar will be needed. I'll send you a PDF via email.

**Comment by SimonGreenhill** [comment]
Danke!

**Comment by chrzyki** [comment]
Done in Concepticon (https://github.com/concepticon/concepticon-data/commit/a39b2d3ff5438e42d4a89794e189945726e2e0fa) and Lexibank (https://github.com/lexibank/backstromnorthernpakistan).
