### ISSUE TITLE
Strict separation between automatic and manual work on data

### ISSUE THREAD

**Issue by chrzyki** [lexibank/lexibank#40]
_From @LinguList on December 3, 2016 13:57_

We have been discussing this in various posts, but I consider it important to restate it and work on a way to implement it in lexibank. The general idea is to strictly distinguish automatic and non-automatic checks when preparing data. This includes:

* concept mapping: use concepticon concept_map, as this is intuitively the best [yet we might want to test it], for automatic concept mapping, or provide a list of concepts.csv or the link to concepticon otherwise
* phonetic transcriptions: select one of the available sound-class schemas in lingpy (asjp, ipa, fuzzy-ipa), to check lingpy compatibility automatically, use an orthography profile for a manual statement, and links to CLPA (this means essentially, we should give up the automated clpa-checks, as they, for example, don't make sense in asjp)
* cognate sets: use Turchin et al. method for automated cognate judgments, if data passes lingpy's quality assessment threshold (arbitrary, but let's say: 95% of recognized sound types and tokens), provide cognate sets otherwise
* alignments: use SCA alignment algorithm if data passes 95% type/token lingpy-check, or provide manual alignments

We can further discuss further aspects in this issue, and I'm open for discussions and modifications, yet I consider it important to be transparent about it in the context of lexibank.

_Copied from original issue: glottobank/lexibank-data#123_

**Comment by chrzyki** [comment]
_From @chirila on December 5, 2016 18:1_

Didn't we talk about bronze/silver/gold standards - where bronze was
automated, silver had some general cleanup, and gold had been fully
proofed?

On Sat, Dec 3, 2016 at 8:57 AM, Johann-Mattis List <notifications@github.com
> wrote:

> We have been discussing this in various posts, but I consider it important
> to restate it and work on a way to implement it in lexibank. The general
> idea is to strictly distinguish automatic and non-automatic checks when
> preparing data. This includes:
>
>    - concept mapping: use concepticon concept_map, as this is intuitively
>    the best [yet we might want to test it], for automatic concept mapping, or
>    provide a list of concepts.csv or the link to concepticon otherwise
>    - phonetic transcriptions: select one of the available sound-class
>    schemas in lingpy (asjp, ipa, fuzzy-ipa), to check lingpy compatibility
>    automatically, use an orthography profile for a manual statement, and links
>    to CLPA (this means essentially, we should give up the automated
>    clpa-checks, as they, for example, don't make sense in asjp)
>    - cognate sets: use Turchin et al. method for automated cognate
>    judgments, if data passes lingpy's quality assessment threshold (arbitrary,
>    but let's say: 95% of recognized sound types and tokens), provide cognate
>    sets otherwise
>    - alignments: use SCA alignment algorithm if data passes 95%
>    type/token lingpy-check, or provide manual alignments
>
> We can further discuss further aspects in this issue, and I'm open for
> discussions and modifications, yet I consider it important to be
> transparent about it in the context of lexibank.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_glottobank_lexibank-2Ddata_issues_123&d=CwMCaQ&c=-dg2m7zWuuDZ0MUcV7Sdqw&r=txIBEahJtVOMk6mnG4D_VV5ZS3ctKFDl3g5FNfiN4cs&m=9E80kClzLjNJp5nWkG0e279CDTVKsCCXAXvowQL29Kg&s=qd13SzX9HY6gUNbzfiN9r4zNiX9oSN7BIF0QgDbVzEU&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AP8oR4PDp1Mb9Dpk-2DABmvZQho6CGrdl9ks5rEXVHgaJpZM4LDTH9&d=CwMCaQ&c=-dg2m7zWuuDZ0MUcV7Sdqw&r=txIBEahJtVOMk6mnG4D_VV5ZS3ctKFDl3g5FNfiN4cs&m=9E80kClzLjNJp5nWkG0e279CDTVKsCCXAXvowQL29Kg&s=LeA26WNCOHyaqBIhbV1am_O6I8EIOY2pPM0awIaw1c0&e=>
> .
>



-- 

Claire Bowern
Associate Professor
Director of Graduate Studies
Department of Linguistics
370 Temple St, Rm 313
New Haven, CT  06511
Support the Endangered Language Fund!: http://smile.amazon.com/ch/06-1459207
.

**Comment by chrzyki** [comment]
_From @LinguList on December 5, 2016 18:43_

Yes, you are completely right, but so far, I'd say, we were not
practicing it for concepts. Currently, I'd say, we have a mix of Gold
and Bronze not indicated, so this is a mere reminder that we need to
indicate it for Bronze in concepts...

**Comment by SimonGreenhill** [comment]
I think this can be closed now as we have the /raw/ and /etc/ directories.
