### ISSUE TITLE
Dataset: Add rest of data from QLC resource - Z'graggen 1980

### ISSUE THREAD

**Issue by chrzyki** [lexibank/lexibank#43]
_From @SimonGreenhill on January 5, 2017 19:29_

Most are short bilingual wordlists mapping from Spanish to some South American language. 

But there are two fantastic ones -- kraft1981 which contains a 434 item wordlist for 68 Chadic languages, and zgraggen1980 (which is also in TNG.org, but this will give us a cross-validation).

_Copied from original issue: glottobank/lexibank-data#163_

**Comment by chrzyki** [comment]
_From @LinguList on January 5, 2017 21:37_

and we have both Kraft and Zgraggen in Concepticon...

**Comment by SimonGreenhill** [comment]
We've got kraft already and Z80 from a different source.
