### ISSUE TITLE
Blacklist for `Dataset.clean_form`

### ISSUE THREAD

**Issue by chrzyki** [lexibank/lexibank#46]
_From @xrotwang on January 26, 2017 12:13_

The default implementation of `Dataset.clean_form` should remove characters from a blacklist. This blacklist should include what was previously stripped by CLPA:
```python
['\u0361', '\u035c', '\u0301']
```

_Copied from original issue: glottobank/lexibank-data#215_

**Comment by SimonGreenhill** [comment]
This is a per-dataset problem, right?
