### ISSUE TITLE
win compatibility

### ISSUE THREAD

**Issue by chrzyki** [lexibank/lexibank#50]
_From @xrotwang on March 1, 2017 5:5_

We can not assume that `lexibank` runs in a shell with a UTF-8 locale (on win it may be cp850 instead).

_Copied from original issue: glottobank/lexibank-data#242_

**Comment by chrzyki** [comment]
_From @xrotwang on March 1, 2017 20:30_

Reading the information for the [win-unicode-console](https://github.com/Drekin/win-unicode-console) package it appears as if this problem could (and should) be solved outside of our own code.

**Comment by SimonGreenhill** [comment]
This problem has been mitigated as lexibank is now only needed for curation. Closing this, any specific issues regarding this should be opened in https://github.com/lexibank/pylexibank/
