### ISSUE TITLE
Best Candidates for Orthography Profile Creation

### ISSUE THREAD

**Issue by chrzyki** [lexibank/lexibank#51]
_From @LinguList on March 13, 2017 6:51_

It is much easier to test the quality of datasets now, so we should make good plans on the creation of orthography profiles for important candidates. The basic would be, as always, the automatic creation of profiles, the testing, where it might work, etc. In contrast to the global approach, we should, as mentioned in #244, also opt for a partial approach, where we create ortho-profiles for best parts of a dataset. I have illustrated how current code can be hacked by using not one profile, but lingpy's built-in commands for segmentation, which you can find here:

* https://github.com/LinguList/lexibank-data/blob/master/datasets/ids/__init__.py#L36

Essentially, three clean-form commands are used, one that ignores the data, one that uses unidecode for Russian transcriptions, and one that expects a normal phonetic string. This shall be discussed, but as part of issue #244. In principal, however, it illustrates that it is possible to also use different orthography profiles (or columns in a profile!) to account for different parts in the data.

Here, we now assemble best candidates to be equipped either with orthoprofiles or with smaller hacks, as in IDS to increase coverage for words accepted in LingPy. 
 

_Copied from original issue: glottobank/lexibank-data#245_

**Comment by chrzyki** [comment]
_From @LinguList on March 13, 2017 7:14_

- [ ] ABVD, subset of Blust's data, could be identified by looking up the metadata for the source (which is often "Blust...")
- [ ] Chirila, needs refinement, as there are many strange symbols, like "\", etc., but since many are recurrent, even simple their replacement may have a great impact on how the data can be read by machinese
- [ ] galuciotupi, could be easily enhanced by quickly adjusting the very small orthoprofile
- [ ] grollemundbantu, is problematic, but people experienced with Bantu languages could probably help
- [ ] huntergatherer, is highly difficult, and contains many bad entries, where comments have been added inside where we expect the lexeme, furthermore, the slash symbol is used as a sound symbol and has been interpreted as a division symbol by us, so needs to be cleaned up or discarded
- [ ] ids has been hacked so far, which increases its reliability, but collaboration with experts for parts of the data would be useful to account for specific conversions, like, e.g., Caucasian languages, where we expect a uniform transcription
- [ ] kraft, has a seemingly straightforward orthography, but the profile is long, with 500 lines, and ideally an expert for those langauges should work on it (it is  agreat resource due to the large concept list)
- [ ] kitchensemitic could be partially added, but those languages where there are only consonants in the orthography need to be excluded, clear case for a split-treatment policy
- [ ] leejaponig needs an official orthoprofile, straightforward for japanologists,  I guess,
- [ ] mayanbvd, what's the status here? seems to be possible to clean this up, but do we have somebody who could help?
- [ ] sidwellaustroasiatic, probably best treated by separating languages, as some are regular and easy, while others are difficult
- [ ] wheelerutoaztekan, straightforward, but expert should look at data
- [ ] wold, need to identify languages with consisten transcriptions

**Comment by chrzyki** [comment]
_From @chirila on March 13, 2017 19:19_

For chirila, give me a list of characters and I'll clean it next week. I suspect hunter gatherer will be trickier, but I can have a go. The Australian hunter-gatherer data is all in chirila though

**Comment by chrzyki** [comment]
_From @LinguList on March 13, 2017 19:49_

The list with the actual treatment is here:
* https://github.com/glottobank/lexibank-data/blob/master/datasets/chirila/TRANSCRIPTION.md

There are quite some questionable cases, where we don't understand, so help would be really appreciated.

**Comment by chrzyki** [comment]
_From @chirila on March 17, 2017 21:31_

Ok, will check next week when I'm back at my computer.

**Comment by SimonGreenhill** [comment]
I think we can close this now, since we did a lot of these ones last year.
