### ISSUE TITLE
clean cache upon fresh install

### ISSUE THREAD

**Issue by chrzyki** [lexibank/lexibank#52]
_From @LinguList on March 15, 2017 12:9_

Is this straightforward, to clean the cache if we install pylexibank? The reason is: I just had the old cache where glottolog-macroareas were still strings, and only now learned that it was the cache that kept the old version. Ideally, when installing lexibank, we should clean all that is inside the cache to make sure that we have the most recent version. Otherwise, bug-chasing will be hard (as I know from lingpy). Alternatively, we just issue a warning, and keep this in mind as a potential error-source...

_Copied from original issue: glottobank/lexibank-data#252_

**Comment by chrzyki** [comment]
_From @xrotwang on March 15, 2017 12:11_

At the very least we should have a `lexibank` command to clean the cache.

**Comment by SimonGreenhill** [comment]
Closed as this no longer applies.
