### ISSUE TITLE
Provider: Convert transnewguinea to a provider

### ISSUE THREAD

**Issue by chrzyki** [lexibank/lexibank#53]
_From @SimonGreenhill on March 15, 2017 15:29_

And extract the major datasets from it. This will make it easier to have orthography profiles etc. 

_Copied from original issue: glottobank/lexibank-data#254_

**Comment by chrzyki** [comment]
_From @LinguList on March 15, 2017 15:30_

very good point!

**Comment by chrzyki** [comment]
_From @SimonGreenhill on April 19, 2017 14:31_

Some of the TNG.org sources are in concepticon already e.g. 

* Bromley-1967-111.tsv
* Clouse-1993-71.tsv
* ConradandDye1975-102.tsv
* Daniels-2016-85.tsv
* Dye-1968-120.tsv
* Hooley-1971-128.tsv
* McElhanon-1967-140.tsv
* Miedema-1985-40.tsv
* Voorhoeve-1975-40.tsv
* Zgraggen-1980-380.tsv

**Comment by SimonGreenhill** [comment]
Closing for now.
