### ISSUE TITLE
Sources: Parse ASJP sources

### ISSUE THREAD

**Issue by chrzyki** [lexibank/lexibank#54]
_From @SimonGreenhill on March 22, 2017 8:23_

The sources are parsed and stored in the [ASJP webapp](http://asjp.clld.org/sources) so we should be able to get them too.

_Copied from original issue: glottobank/lexibank-data#256_

**Comment by chrzyki** [comment]
_From @xrotwang on March 22, 2017 8:24_

And I even know the person who did that!

**Comment by SimonGreenhill** [comment]
Moved to https://github.com/lexibank/asjp/issues/1
