### ISSUE TITLE
Dataset: DiACL

### ISSUE THREAD

**Issue by chrzyki** [lexibank/lexibank#55]
_From @SimonGreenhill on March 27, 2017 8:32_

Gerd Carling et al's [DiACL](https://diacl.ht.lu.se/) is now public. This has [>500 languages](https://diacl.ht.lu.se/Language/Index), [multiple wordlists](https://diacl.ht.lu.se/WordList/Index)

Looks like there's a usable API [here](https://diacl.ht.lu.se/Project/XmlJson) so it should be easy to add them as a provider.

_Copied from original issue: glottobank/lexibank-data#258_

**Comment by chrzyki** [comment]
_From @LinguList on March 27, 2017 8:41_

Nice how they call it "Swadesh" and do not use the same glosses: https://diacl.ht.lu.se/WordListCategory/Details/100 (e.g., "foot not leg"). Just added this to Concepticon as [Issue #304](https://github.com/clld/concepticon-data/issues/304). From there, you'll see that we need a good idea on how to add the concept lists.

Another potential problem (not a problem, but what we need to find out), is that they draw from IDS, so the question is: how much data is new, how much is it changed, etc. Actually quite interesting...

**Comment by chrzyki** [comment]
_From @LinguList on March 27, 2017 8:43_

Funny also: https://diacl.ht.lu.se/WordListItem/Details/3010 shows that many items are just empty.

**Comment by SimonGreenhill** [comment]
done.
