### ISSUE TITLE
Direct Bibliography Integration from Glottolog API

### ISSUE THREAD

**Issue by chrzyki** [lexibank/lexibank#57]
_From @LinguList on March 29, 2017 9:55_

Glottolog's various bibtex files allow for quick referencing, as they preserve the original keys. I suggest that we include EvoBib in Glottolog, but also add an additional lexibank.bib, so that we can add those references which we do not find in either of the references.

_Copied from original issue: glottobank/lexibank-data#262_

**Comment by SimonGreenhill** [comment]
Closed in favor of https://github.com/lexibank/pylexibank/issues/16
