### ISSUE TITLE
Segmentation: Add for Polynesian

### ISSUE THREAD

**Issue by chrzyki** [lexibank/lexibank#59]
_From @LinguList on March 30, 2017 10:19_

I just talked to Mary in our institute, and she recommended given that she cognatized and worked on Polynesian languages, that we start with those and also run a test on cognate detection evaluation. I'd say, we could do this by:

a) extracting the polynesian languages she worked on
b) make a first small orthography profile (discuss it back with her)
c) add initial alignments

This would give us the possibility to have a first well-represented part of ABVD, we could discuss the quality of our algos, and we could check the power of alignments also in representation etc. for linguists. This would be a very computer-assisted procedure.

_Copied from original issue: glottobank/lexibank-data#267_

**Comment by SimonGreenhill** [comment]
Closing this. @LinguList we can add Mary's work as a new dataset when that paper is published.
