### ISSUE TITLE
Dataset: Michael Dunn's Data on Aslian languages?

### ISSUE THREAD

**Issue by chrzyki** [lexibank/lexibank#66]
_From @LinguList on May 3, 2017 18:44_

@evoling, just remembered your data on Aslian languages and found your paper (http://evoling.net/pdfs/Dunn_2013_Human_Biology.pdf). Would you share that with us to support the lexibank enterprise? I remember you even tested lingpy on it, so it IS in some kind of phonetic encoding, right? 

_Copied from original issue: glottobank/lexibank-data#279_

**Comment by chrzyki** [comment]
_From @evoling on September 15, 2017 11:45_

They're already done a lot of work on it (attached). Is there any way that can be preserved (if necessary I'll transcribe their corrections), but automatic would be better...

M

On 2017-09-15, 13:39, "Johann-Mattis List" <notifications@github.com<mailto:notifications@github.com>> wrote:


Update: for the orthography profile, we'll have to create one for each language, so @evoling<https://github.com/evoling> can ask the collaborators to work on this. Alternatively, I may create one before that shows all data, but gives information on examples with the language involved.

**Comment by chrzyki** [comment]
_From @LinguList on September 15, 2017 12:23_

can't see the attachment, if there remain a few dubious cases, we may better just extract the instances and show them. Maybe just plug the stuff into EDICTOR and show them, so they can just check easily which instances are problematic. I can later show how to do that.

**Comment by chrzyki** [comment]
_From @LinguList on September 15, 2017 12:23_

Yes, maybe paste the attachment in the field here as txt format (but you'll need to log in via the browser).

**Comment by chrzyki** [comment]
_From @evoling on September 15, 2017 13:38_

They've annotated it in colour, in excel. I'll send it you you by email to take a look at -- just tell me how best to proceed. Michael

On 2017-09-15, 14:23, "Johann-Mattis List" <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, maybe paste the attachment in the field here as txt format (but you'll need to log in via the browser).

**Comment by chrzyki** [comment]
_From @xrotwang on September 15, 2017 13:56_

send the excel. reading out the color information programmatically shouldn't be a problem.

**Comment by chrzyki** [comment]
_From @LinguList on September 15, 2017 14:56_

I thought those Aslian were Austronesian langauges, which is why I was confused, but now that I saw that they are [Austro-Asiatic](https://en.wikipedia.org/wiki/Aslian_languages), I understand why they insist on many of those strange words being "segmental". The problem is that their phonetic transcription is a mix of phonological and phonetic annotation. The word "pnhdəh" for example is probably pronounced as "pənəhedəh" or similar, but it is not obvious for me how to resolve these weak syllables, since normally, phonological rules in those languages are easy to be spotted and should not involve that many segments (e.g., "pna" is pronounced as "pana" with short first syllable). One could leave it phonemic, but on the other hand, it is not clear what the status of segments like "th" is, as this could either be aspirated or some weak syllable.

Obviously, if checking with [clts](http://calc.digling.org/clts/), there are further IPA problems: what is the meaning of "r" in "kntrɔɔŋ", etc., as this is not a proper IPA symbol.  There are more cases of this, also typical confusables. They are all easy to handle with the tools we have, but we'd need to have more examples on how things like "kntr'ɔɔŋ" or "pnhdəh" should be segmented.

If we re-do the profiles from scratch for each language, it'll be very difficult preserving information that was originally done, and I would not want to spend my time on this. As the current version still has too many unresolved questions, I propose to start from scratch, but by adding language-specific information, as well as information on proper-IPA characters, this will be much easier to correct.

@evoling, you could maybe introduce your collaborators to us so we can discuss this either via github or in emails. In this way, I can ask direct questions in those cases where I don't understand, and we may proceed more efficiently.

**Comment by SimonGreenhill** [comment]
avaliable here: https://github.com/lexibank/dunnaslian
