### ISSUE TITLE
Dataset: Lexiruhma Data 

### ISSUE THREAD

**Issue by chrzyki** [lexibank/lexibank#70]
_From @LinguList on June 19, 2017 17:45_

* https://github.com/lessersunda/lexirumah-data/releases/tag/Lexirumah-20170619

Nice data, aligned with EDICTOR, etc., already linked to concepticon! Gereon Kaiping did an excellent job, I'd say.

_Copied from original issue: glottobank/lexibank-data#285_

**Comment by chrzyki** [comment]
_From @LinguList on September 2, 2017 10:47_

- [ ] refine concepticon mapping
- [ ] ask providers to put on zenodo and help us properly quote it
- [ ] check some potential errors of the data

The data is huge: some 50+ languages, with 800+ concepts each! All already linked to glottolog (but should also be checked) and concepticon (unfortunately, automatic mapping, no user-refinement, needs checking).

**Comment by chrzyki** [comment]
_From @LinguList on September 4, 2017 17:32_

New source is here: http://www.model-ling.eu/

They published officially in CLLD framework.

**Comment by chrzyki** [comment]
_From @LinguList on September 4, 2017 17:33_

The alignments seem to have some errors, I already submitted an issue on this topic.

**Comment by Anaphory** [comment]
I just noticed this. We have a second version now, with more languages, but no cognate codes for the moment – I am comparing several coding methods and I will use whichever turns out best for version 2.1.0, tell me if you need anything else.

**Comment by LinguList** [comment]
Yes, very nice, we'll be in touch with you soon on this. @xrotwang, I suggest, we include Gereon and Lexiruhma into the clics update and our plan for sci-data. Would be nice in terms of having more coverage, I guess...

**Comment by SimonGreenhill** [comment]
This is added.
