### ISSUE TITLE
Dataset: Add the Swadesh Lists from Wiktionary

### ISSUE THREAD

**Issue by chrzyki** [lexibank/lexibank#71]
_From @LinguList on June 24, 2017 11:10_

They should be mostly generic enough to be parsed, as they all use their own template. One could just add them all, not link them phonetically, unless they ahve the IPA column, etc. It will be interesting to compare (also the quality, which is often NOT trusted by experts), but also provide an interesting example of the different sources which lexibank can deal with.

_Copied from original issue: glottobank/lexibank-data#287_

**Comment by chrzyki** [comment]
_From @tresoldi on June 24, 2017 12:20_

I could probably do it, it would also be a way to get back to my Wiktionary parser (cf.: [here](https://github.com/tresoldi/wiktionary_parser))

**Comment by chrzyki** [comment]
_From @LinguList on June 24, 2017 12:56_

I think, the core would be the download function in lexibank: parse the page, get the data, and store it in some intermediate format. But it's of not a high priority to us for the moment, just a thing I think we should keep in mind.

**Comment by chrzyki** [comment]
_From @tresoldi on June 24, 2017 13:28_

You mean something like running `lexibank download WIKISWADESH` from the command line for the full process of dowload/parse/output, right? I've tried something similar in the past and failed. Unfortunately, Wiktionary pages are too messy and inconsistent in their organization, as well as subject to arbitrary changes in the HTML/CSS code from time to time; even the XML sources are far from well formed and normalized (in fact, I decided to parse them as text-files, taking care of the structure on my own).

But I am talking more of the full contents of the Wiktionary, not only Swadesh lists, so I see your point. An idea could be to write a Wiktionary bot to populate the Swadesh lists from its own contents (if you look at the histories, they are almost all edited by hand, with redundant information). It would actually be a good way to make lexibank more popular.

In any case, I'll go back to my parser and drop you a line when I have something that I believe could be used as an intermediate source, so we can go on discussing.

**Comment by chrzyki** [comment]
_From @LinguList on June 24, 2017 13:36_

> But I am talking more of the full contents of the Wiktionary, not only Swadesh lists, so I see your point. An idea could be to write a Wiktionary bot to populate the Swadesh lists from its own contents (if you look at the histories, they are almost all edited by hand, with redundant information). It would actually be a good way to make lexibank more popular.

This sounds cool, but it has already been done, there is some NLP application, not on Swadesh lists but all data (I think they presented it at one of those lrec conferences), where they make an etymological dictionary out of it, and we'd have problem in finding the glosses, as they would need some fuzzy matches, etc., which is a publication or an application of its own. Since lexibank only includes sources which are published somehow, we can't make our own application to populate data, but would need to have an external published application which provides the data in a form in which it could easily be included into lexibank.

The Swadesh lists in wiktionary are normalized regarding concepts, they are linked to concepticon, and they have tables with numbers for the concepts, so identifying those should work for at least a couple of languages. 

But as I said, priority is very low here, and it is just to keep this in mind to maybe look into it  whenever we think we need another easy-to-add dataset (e.g., because we're short one to get an even number, etc.).

**Comment by chrzyki** [comment]
_From @tresoldi on June 24, 2017 15:16_

> Since lexibank only includes sources which are published somehow, we can't make our own application to populate data, but would need to have an external published application which provides the data in a form in which it could easily be included into lexibank.

Only using published data makes a lot of sense, but would probably limit most Swadesh lists on Wiktionary. You can see that few of them list any source, and even in cases when they do list them, the entries have usually been edited since the referenced transcription (like for Egyptian Arabic, check the edit history). Maybe directly scrap the data from on-line version of published dictionaries?

**Comment by chrzyki** [comment]
_From @LinguList on June 24, 2017 15:49_

No, as this as been done by other people and it would be again be another publication ("swadeshl lists created from dictionaries"), again not the goal of lexibank, as lexibank does not offer new sources, but only published sources, such as genebank in biology. Since Wiktionary Swadesh lists are there online in a state that they can both be quoted and are versionized, one can treat them as another repository for lexibank, but only if one leaves the data untouched. If we started making another list of Swadesh lists by taking them from sources, we'd have to publish this first, in order to then include it into lexibank, it would not be a target repositoriy of lexibank, no new dataset...

**Comment by chrzyki** [comment]
_From @tresoldi on June 24, 2017 15:55_

Oh, ok, it is clearer now -- I was taking "published" as "(academically) peer reviewed". This way, the versions from Wiktionary could even be timestamped and permalinked. If I get further with my scraping and the code can be reused, I'll let you know.

**Comment by chrzyki** [comment]
_From @LinguList on June 24, 2017 15:56_

;-) sorry if it was not precise enough.

**Comment by SimonGreenhill** [comment]
I'm going to close this now as I can see this being a big moving target, and I'd rather have well-provenienced data that we can track to a source (rather than "wikipedia"). These lists also seem to be coming in in chunks of related languages anyway, so I think this is better handled as a specific issue related to specific language samples
