### ISSUE TITLE
libreoffice dependency for doc files (cals)

### ISSUE THREAD

**Issue by chrzyki** [lexibank/lexibank#77]
_From @SimonGreenhill on July 25, 2017 7:32_

Can't install `cals` without libreoffice installed. 

We should document this and raise an error in `cals` cmd_install if libreoffice is not found. 

On the other hand, it's a massive dependency to rely on, but there's no other way around it is there ([antiword](http://www.winfield.demon.nl/))? (unless we can convert it ourselves and store the converted file in lexibank). 

_Copied from original issue: glottobank/lexibank-data#294_

**Comment by chrzyki** [comment]
_From @xrotwang on July 25, 2017 7:45_

True, maybe we should handle `cals` the way we handle `galuciotupi`:
```python
    def cmd_download(self, **kw):
        print("""
Download the PDF from here:
http://www.scielo.br/pdf/bgoeldi/v10n2/2178-2547-bgoeldi-10-02-00229.pdf
and extract the text running a command like below:
pdftotext -raw galucio-tupi.pdf galucio-tupi.txt
""")
```

**Comment by chrzyki** [comment]
_From @SimonGreenhill on July 25, 2017 8:21_

I guess this is a policy type decision for us to make. Do we want to:

1. Do whatever it takes to get the data into lexibank (i.e. use libreoffice or whatever is needed) and fail appropriately if the user doesn't have the required tool ("please install X to use this dataset). 
- Pros: More data.
- Cons: Could get complex toolchains, could add platform issues (i.e. any system call to a binary needs to be handled differently on *nix vs windows), could add version fun with different external tools (e.g. a new version of libreoffice changes output slightly?). Need to do more work to handle error conditions (e.g. `lexibank install` crashes for me because it can't succeed with `cals`).

2. Preprocess the data as required and store the intermediate step in lexibank. Lexibank download/install uses the intermediate, and we document that the intermediate file was created by "pdftotext -raw galucio-tupi.pdf galucio-tupi.txt" using pdftotext version xyz.
- Pros: More data, and simpler toolchain. Data are safe in git and not at mercy of program changes.
- Cons: Storing intermediate data could be problematic (is it republishing data?)

3. Tell the user how to get it (e.g. the `galuciotupi` solution) and leave it up to the user.
- Pros: less work for us. 
- Cons: less data immediately available, risk of different galuciotupi's depending on what version of program X the user uses. Support problems ("I can't install galuciotupi on CentOS v1 that has an archaic pdftotext v0.01a" please help!).

I like 2 but the con is a big one. Thoughts?

**Comment by chrzyki** [comment]
_From @xrotwang on July 25, 2017 8:42_

I like 2, too. And the con just highlights inappropriate primary publishing formats! I'd describe our policy in this regard as "See what you make us do if you publish in these formats?"

So, in terms of a stated policy, I'd say: Raw data must be available in parse-able (text-based) formats, where parse-able means can be read with 20 lines of python + standard library code. This still leaves us with some edge cases, like `tls` which is read from a DBF file.

We might also want to adopt a general republishing strategy. I.e. should we put pre-parsed data sources on ZENODO - and feed them from there into the general lexibank workflow?

**Comment by chrzyki** [comment]
_From @xrotwang on July 25, 2017 8:47_

Regarding TLS, I'd definitely opt for us putting a CSV dump of the DBF file on ZENODO under a CC-BY-NC license, which seems to be in line with [CBOLD](http://www.linguistics.berkeley.edu/~jblowe/CBOLD/), where the data is published, too (and from where it may disappear at some point, I guess).

**Comment by chrzyki** [comment]
_From @SimonGreenhill on July 28, 2017 13:58_

- [ ] Write a brief policy document containing this
- [ ] Refactor `cals`
- [ ] Refactor `galuciotupi`

**Comment by SimonGreenhill** [comment]
I think this problem also goes away now we're storing the CLDF data. This is just an issue for the dataset curator. 

Perhaps we can have a policy that datasets where this is necessary store the intermediate data in /etc?

**Comment by xrotwang** [comment]
I'd store the intermediate data in `raw/` as well - running a command in the shell isn't a big contribution. It would also make the "in `cmd_install` data is read from `raw` and written to `cldf`" convention invalid.

**Comment by SimonGreenhill** [comment]
Yes, good point. I've added this to the wiki on policies.

**Comment by SimonGreenhill** [comment]
We now store the intermediate artifacts in raw, so this is no longer an issue unless you want to blow away ./raw/ and start again
