### ISSUE TITLE
Add language mapping for Malagasy dialects

### ISSUE THREAD

**Issue by chrzyki** [lexibank/lexibank#78]
_From @SimonGreenhill on August 15, 2017 7:58_

https://github.com/glottobank/lexibank-data/tree/master/datasets/malagasy

_Copied from original issue: glottobank/lexibank-data#300_

**Comment by SimonGreenhill** [comment]
Done in https://github.com/glottobank/lexibank-data/commit/66947fa0841e153e4a3bbea02e3addaa6c79b3c1
