### ISSUE TITLE
Extract "clean" subsets from `abvd` into separate datasets

### ISSUE THREAD

**Issue by chrzyki** [lexibank/lexibank#82]
_From @xrotwang on August 31, 2017 6:29_

E.g. the polynesian data - complemented with orthography profiles.

_Copied from original issue: glottobank/lexibank-data#310_

**Comment by chrzyki** [comment]
_From @chirila on August 31, 2017 15:3_

That would be awesome (having used AVBD for class datasets and being stumped by how to interpret digraphs vs clusters in some of these languages).

**Comment by SimonGreenhill** [comment]
Not worth it at this stage, and the polynesian data will be published elsewhere (at which point it can be included as a new dataset).
