### ISSUE TITLE
benuecongo

### ISSUE THREAD

**Issue by chrzyki** [lexibank/lexibank#86]
_From @xrotwang on August 31, 2017 9:3_

- [ ] add citation
- [ ] write dataset description
- [ ] concepticon mapping: identify original source, then add list to Concepticon

This dataset is mainly in lexibank, because it seems to be unmaintained at its current location (potential maintainer contacted but no reply).

_Copied from original issue: glottobank/lexibank-data#316_

**Comment by chrzyki** [comment]
_From @LinguList on August 31, 2017 9:56_

see the about page for quoting the people as providers: http://comparalex.org/index.php?page=about

**Comment by SimonGreenhill** [comment]
added.
