### ISSUE TITLE
csd

### ISSUE THREAD

**Issue by chrzyki** [lexibank/lexibank#91]
_From @LinguList on August 31, 2017 9:26_

- [ ] concepticon mapping (at least subset)
- [ ] add cognate sets
- [ ] add description in notes.md, indicating that concepts refer to the proto-forms
- [ ] tag as etymological dictionary

_Copied from original issue: glottobank/lexibank-data#323_

**Comment by SimonGreenhill** [comment]
Closed in favor of specific dataset issues.
