### ISSUE TITLE
Lexibank to EDICTOR

### ISSUE THREAD

**Issue by chrzyki** [lexibank/lexibank#95]
_From @thiagochacon on September 3, 2017 18:37_

At some point, it will be useful to have a way to transform one or multiple datasets into a file that can be upload to EDICTOR

_Copied from original issue: glottobank/lexibank-data#331_

**Comment by chrzyki** [comment]
_From @LinguList on September 14, 2017 11:25_

Yes, we will need commands in the form

```
$ lexibank --format=edictor export dataset
```

We are also working on nexus export as a generic feature of cldf: https://github.com/glottobank/pycldf/issues/21

I suppose that we handle export to current lingpy as well as edictor in a generic way from there.

**Comment by SimonGreenhill** [comment]
Isn't this a problem that should be solved by EDICTOR (load/save CLDF)?
