### ISSUE TITLE
Language archives as resources for lexibank and clts

### ISSUE THREAD

**Issue by chrzyki** [lexibank/lexibank#96]
_From @thiagochacon on September 11, 2017 20:59_

There are a number of websites with sounds and transcriptions of word lists, which could be added at some point to Lexibank. 

For instance, 
IPA-ILLUTRATIONS
https://richardbeare.github.io/marijatabain/ipa_illustrations_all.html (linked from the site from the IPA https://www.internationalphoneticassociation.org/content/journal-ipa)

UCLA PHONETIC LAB ARCHIVES
http://archive.phonetics.ucla.edu/

I wonder whether at some point the audio files linked to symbols in the transcription could also illustrate CALC...

In addition, I am not sure productive it would be, but there are other archives from projects of language documentation that have loads of lexical and audio data. But I guess the data is not in an easy or open format to be used. For instance those listed here http://www.rnld.org/archives

_Copied from original issue: glottobank/lexibank-data#334_

**Comment by chrzyki** [comment]
_From @LinguList on September 13, 2017 5:35_

I'd say, these things are less for lexibank, but more for [clts](http://github.com/lingpy/clts) as these are sounds, right?

**Comment by chrzyki** [comment]
_From @thiagochacon on September 13, 2017 9:20_

not at all. there are lots of lexical resources there too.

check the Amharic (amha1245) language page for instance 
http://archive.phonetics.ucla.edu/Language/AMH/amh.html

**Comment by SimonGreenhill** [comment]
Closing this as they're outside lexibank (but cool resources we should use).
