### ISSUE TITLE
Orthography Profile: galuciotupi

### ISSUE THREAD

**Issue by chrzyki** [lexibank/lexibank#97]
_From @thiagochacon on September 6, 2017 12:20_

The orthography profile for dataset galuciotupi is almost ready, but there are a few remaining issues:

* the grapheme c probably has more than one value in different languages, so we need a way to change it accordingly in each language

* the symbos ~ is indicating alternating forms as in fomr  galuciotupi-904  ta̤bə́ ~ na̤bə́

please adivse how to proceede here, since the forms seem not be parsed as a single form, while they are actually variants

* finally, many words were not tokenized because they have parentheses or brackets, e.g. pe(e) or o-pi [obi]. This is indeed a recurrent problem, so we will need to find ways to handle this in a more straightforward way.

_Copied from original issue: glottobank/lexibank-data#333_

**Comment by chrzyki** [comment]
_From @LinguList on September 6, 2017 14:47_

very good.

well, what code did you run to create the orthoprofile?

Or did you use the one we already put in there?

Note that we can automatically strip off brackets when converting from Value to Form, and we have also the policy to take only one of the variants (or list two in separate rows, but I personally prefer to include them). The good thing is: users who re-work on the data, can look into the field "Value", where they see the original form, and also, what we excluded, so one can manually refine a variant easily.

**Comment by chrzyki** [comment]
_From @thiagochacon on September 8, 2017 10:38_

I used the file that was already in the folder. I am attaching it here in case you want to have a look. If you give the correct code, I can try to generate a new orthoprofile. But in the code, we need a step where all /)] etc. are deleted before tokenization.
 
Regarding alternate forms, I personally prefer that each form has its own row. 

[orthography.txt](https://github.com/glottobank/lexibank-data/files/1287586/orthography.txt)

**Comment by chrzyki** [comment]
_From @LinguList on September 14, 2017 11:20_

Good job, many, there is one remaining thing, the Tilde ~ is <???>, but I suppose this reflects alternate forms, so we need to modify our text-entry-to-form splitter in the base code.

I have little time to work on this now, as I'm in the stage of finalizing the CLTS. But you are making very good progress, @thiagochacon, as our good conscience on the correct handling of SA languages. Excellent work!

**Comment by SimonGreenhill** [comment]
This seems complete here: https://github.com/lexibank/galuciotupi (if not, open an issue there)
